import type { Lead, LeadStatus } from "@/lib/types";
import { fmtDate } from "@/lib/format";
import { Icon } from "@/components/ui/Icon";
import { LeadStatusControl } from "./LeadStatusControl";

const STATUS_STYLE: Record<LeadStatus, string> = {
  new: "border-line bg-canvas text-muted",
  contacted: "border-blue/25 bg-blue/10 text-blue",
  replied: "border-teal-line bg-teal-soft text-teal",
  interested: "border-purple-line bg-purple-soft text-purple",
  qualified: "border-purple-line bg-purple-soft text-purple",
  won: "border-green-line bg-green-soft text-green",
  lost: "border-red-line bg-red-soft text-red",
};

function StatusBadge({ status }: { status: LeadStatus }) {
  return (
    <span
      className={`inline-flex rounded-full border px-2.5 py-0.5 text-[11px] font-semibold capitalize ${STATUS_STYLE[status]}`}
    >
      {status}
    </span>
  );
}

export function LeadsView({
  leads,
  canManage,
}: {
  leads: Lead[];
  canManage: boolean;
}) {
  if (leads.length === 0) {
    return (
      <div className="flex flex-col items-center gap-2 rounded-card border border-dashed border-line bg-surface px-6 py-16 text-center">
        <Icon name="users" size={24} className="text-faint" />
        <p className="text-[14px] font-semibold text-ink">No leads yet</p>
        <p className="max-w-sm text-[12.5px] text-muted">
          Leads generated by your campaigns will appear here as they come in.
        </p>
      </div>
    );
  }

  return (
    <div className="overflow-hidden rounded-card border border-line bg-surface">
      <div className="flex items-center justify-between border-b border-line px-5 py-3">
        <h3 className="text-[13px] font-bold text-ink">
          All leads <span className="num text-faint">· {leads.length}</span>
        </h3>
        {!canManage && (
          <span className="text-[11.5px] text-faint">Read-only</span>
        )}
      </div>
      <div className="scroll-thin overflow-x-auto">
        <table className="w-full min-w-[720px] border-collapse text-left">
          <thead>
            <tr className="border-b border-line text-[11px] font-semibold uppercase tracking-wide text-faint">
              <th className="px-5 py-2.5">Lead</th>
              <th className="px-5 py-2.5">Company</th>
              <th className="px-5 py-2.5">Campaign</th>
              <th className="px-5 py-2.5">Added</th>
              <th className="px-5 py-2.5">Status</th>
            </tr>
          </thead>
          <tbody>
            {leads.map((l) => (
              <tr key={l.id} className="border-b border-line last:border-b-0 hover:bg-hover">
                <td className="px-5 py-3">
                  <div className="text-[13px] font-medium text-ink">{l.fullName || "—"}</div>
                  <div className="num text-[12px] text-faint">{l.email}</div>
                </td>
                <td className="px-5 py-3 text-[12.5px] text-strong">
                  <div>{l.company || "—"}</div>
                  {l.title && <div className="text-[11.5px] text-faint">{l.title}</div>}
                </td>
                <td className="px-5 py-3 text-[12.5px] text-muted">{l.campaignName || "—"}</td>
                <td className="px-5 py-3">
                  <span className="num text-[12.5px] text-muted">{fmtDate(l.createdAt)}</span>
                </td>
                <td className="px-5 py-3">
                  {canManage ? (
                    <LeadStatusControl leadId={l.id} status={l.status} />
                  ) : (
                    <StatusBadge status={l.status} />
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
